### ISSUE TITLE
适配新的教务系统

### ISSUE THREAD

**Issue by Glucy-2** [ArcticLampyrid/njupt_detailed_grades#2]
![图片](https://github.com/ArcticLampyrid/njupt_detailed_grades/assets/53287753/241c4522-5504-43d8-b8b3-3c91378a27f7)
教务系统似乎升级了，读不到了

**Comment by Glucy-2** [comment]
新教务系统不返回原始分力（

**Comment by ArcticLampyrid** [comment]
来自热心网友的消息：
> 教务系统bug都已经捅到学院内部去了  
> 院长直接很好奇学生从哪里得到的平时成绩  
> 因为学生拿着平时成绩直接找到学院里面去
